### ISSUE TITLE
This is not working with latest update from Incapsula

### ISSUE THREAD

**Issue by moeseth** [ziplokk1/incapsula-cracker#1]

**Comment by ziplokk1** [comment]
Can I get a url that's not working to debug with?

**Comment by moeseth** [comment]
http://www.pyithuhluttaw.gov.mm/?q=news/1762

**Comment by ziplokk1** [comment]
checkout the hotfix branch. It should work if using a session object. Unfortunately the IncapSession class is broken but you can use a Session object instead.

``` python
import requests

from incapsula import crack

session = requests.Session()
r = session.get('http://www.pyithuhluttaw.gov.mm/?q=news/1762')
r = crack(session, r)  # unblocked url
```

**Comment by moeseth** [comment]
Thank you
