### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by Kladdkaka** [ziplokk1/incapsula-cracker#3]
Hey!

First off I want to thank you for the library, it looks really cool! :)
I'm just wondering if you could add Python 3 support to the library, I tried to do it myself (being the Python noob that is me, I failed miserably :p), it would really be awesome!

Have a great day!

**Comment by ziplokk1** [comment]
No problem, Give me a few weeks since I'm currently overwhelmed with other projects at the moment but that's been something on my to-do list.

**Comment by Kladdkaka** [comment]
No worries! Thank you so much :) Take your time, I'm not in a hurry or anything at all, feel free to message me in case you would need some help or anything :)

**Comment by ziplokk1** [comment]
Hey Kladdkaka, 

I still haven't had time to get around to looking at adding python3 implementation, but figured I'd let you know I haven't forgotten. If you think you could help with implementing python3 compatibility it would be really appreciated.

Thank you,
Mark

**Comment by Kladdkaka** [comment]
Hello Mark!

Thanks a lot for the reply, I really appreciate it! Although I have to say that I myself don't really need the library anymore, the site (CSGODouble.com) that I was going to use it for got shut down a few days ago, but I think there is probably someone else who would need the library updated for python3, if there is anyway I can help (although I must admit I am a python noob :p) feel free to tell me!

Have a great day!
Erik

**Comment by ziplokk1** [comment]
It's a year late, but [here](https://github.com/ziplokk1/incapsula-cracker-py3) is a python 3 implementation.
